version: '3'

services:
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - net-desafio2
            
    node:
        container_name: node
        build: ./node  
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js     
        volumes:
            - ./node:/usr/src/app
        networks:
            - net-desafio2 
        tty: true    
        depends_on:
            - db   
                
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - 8080:80            
        networks:
            - net-desafio2 
        depends_on:
            - node   
    
networks:    
    net-desafio2:
        driver: bridge  